baseurl = "http://tbenthompson.com/"

theme = "none"

title = "T. Ben Thompson"
author = "T. Ben Thompson"
languageCode = "en-us"

enableRobotsTXT = true

pygmentsUseClassic            = false
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses            = true

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
